# Generated by Django 4.1 on 2022-08-26 00:11

from django.db import migrations

def populate_article_type(apps, schemaeditor):
    a_types = {
        "report": "A journalistic piece",
        "column": "A journalists opinion piece",
        "editorial": "A person that creates columns for the newspaper",
        "editor": "A op piece by an editior",
    }
    ArticleType = apps.get_model("articles", "ArticleType")
    for name, desc in a_types.items():
        at_obj = ArticleType(name=name, description=desc)
        at_obj.save()

def populate_status(apps, schemaeditor):
    statuses = {
        "pending": "An article that has not been reviewed",
        "approved": "An article that has been approved by an editor",
        "rejected": "An article that has been rejected by an editor",
    }
    Status = apps.get_model("articles", "Status")
    for name, desc in statuses.items():
        status_obj = Status(name=name, description=desc)
        status_obj.save()

class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_article_type),
        migrations.RunPython(populate_status)
    ]
